Имеется следующий фрагмент программы:

try:
    val = float(input())
except ValueError as e:
    print(e)
При каких входных данных выполнение программы перейдет в блок except?

при вводе вещественных или целочисленных значений
при вводе не числовых или целочисленных значений
при вводе любых не числовых значений
при вводе не числовых или вещественных значений